"""empty message

Revision ID: 0bb58be7d1d9
Revises: 9630ffa63858
Create Date: 2023-06-06 00:41:52.700792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb58be7d1d9'
down_revision = '9630ffa63858'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_environment_test_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_pattern_found', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_environment_test_logs', schema=None) as batch_op:
        batch_op.drop_column('original_pattern_found')

    # ### end Alembic commands ###
