"""empty message

Revision ID: 30464ea1f91f
Revises: 008c51ac06c4
Create Date: 2023-03-12 01:14:26.732282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30464ea1f91f'
down_revision = '008c51ac06c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predicted_message_language', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log', schema=None) as batch_op:
        batch_op.drop_column('predicted_message_language')

    # ### end Alembic commands ###
