"""empty message

Revision ID: 3e336029f471
Revises: 854d8e455980
Create Date: 2023-05-01 03:34:55.792032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e336029f471'
down_revision = '854d8e455980'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_environment_test_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predicted_score', sa.Numeric(precision=3, scale=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_environment_test_logs', schema=None) as batch_op:
        batch_op.drop_column('predicted_score')

    # ### end Alembic commands ###
