"""empty message

Revision ID: 504c6027929e
Revises: 91225f2e46aa
Create Date: 2023-12-08 22:35:50.552906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '504c6027929e'
down_revision = '91225f2e46aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dev_environment_test_logs',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('reply', sa.String(), nullable=False),
    sa.Column('predicted_language', sa.String(), nullable=False),
    sa.Column('predicted_score', sa.Numeric(precision=3, scale=15), nullable=True),
    sa.Column('pattern_found', sa.String(), nullable=False),
    sa.Column('original_pattern_found', sa.String(), nullable=True),
    sa.Column('pattern_matching_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_lang_correct', sa.Boolean(), nullable=True),
    sa.Column('is_information_retrieved_valid', sa.Boolean(), nullable=True),
    sa.Column('is_query_within_domain', sa.Boolean(), nullable=True),
    sa.Column('test_number', sa.Integer(), nullable=True),
    sa.Column('reconstructed_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('no')
    )
    op.create_table('unique_tester_identifier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usability_test_logs',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('reply', sa.String(), nullable=False),
    sa.Column('predicted_language', sa.String(), nullable=False),
    sa.Column('predicted_score', sa.Numeric(precision=3, scale=15), nullable=True),
    sa.Column('pattern_found', sa.String(), nullable=False),
    sa.Column('original_pattern_found', sa.String(), nullable=True),
    sa.Column('pattern_matching_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_lang_correct', sa.Boolean(), nullable=True),
    sa.Column('is_information_retrieved_valid', sa.Boolean(), nullable=True),
    sa.Column('is_query_within_domain', sa.Boolean(), nullable=True),
    sa.Column('test_number', sa.Integer(), nullable=True),
    sa.Column('reconstructed_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('no')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('log',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('predicted_message_language', sa.String(), server_default='', nullable=False),
    sa.Column('reply', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log')
    op.drop_table('user')
    op.drop_table('usability_test_logs')
    op.drop_table('unique_tester_identifier')
    op.drop_table('dev_environment_test_logs')
    # ### end Alembic commands ###
