"""empty message

Revision ID: 764c00c16833
Revises: a775cf5c0f25
Create Date: 2023-04-27 02:23:20.420375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '764c00c16833'
down_revision = 'a775cf5c0f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_environment_test_logs', schema=None) as batch_op:
        batch_op.drop_column('pattern_reconstructed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_environment_test_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pattern_reconstructed', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
