"""empty message

Revision ID: 854d8e455980
Revises: 764c00c16833
Create Date: 2023-05-01 03:14:24.072098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854d8e455980'
down_revision = '764c00c16833'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_environment_test_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_number', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_environment_test_logs', schema=None) as batch_op:
        batch_op.drop_column('test_number')

    # ### end Alembic commands ###
