"""empty message

Revision ID: 91225f2e46aa
Revises: c82ee203e348
Create Date: 2023-12-07 01:06:49.590826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91225f2e46aa'
down_revision = 'c82ee203e348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unique_tester_identifier', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unique_tester_identifier', schema=None) as batch_op:
        batch_op.drop_column('user_agent')

    # ### end Alembic commands ###
