"""empty message

Revision ID: 9630ffa63858
Revises: 36435ee8fecd
Create Date: 2023-05-30 05:23:33.931452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9630ffa63858'
down_revision = '36435ee8fecd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_environment_test_logs', schema=None) as batch_op:
        batch_op.drop_column('predicted_dimension_number')
        batch_op.drop_column('predicted_dimension_label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dev_environment_test_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predicted_dimension_label', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('predicted_dimension_number', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
