"""added model DevEnvironmentTestLogs which contains the dev test logs

Revision ID: a775cf5c0f25
Revises: b617e1951d6b
Create Date: 2023-04-26 20:37:29.444217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a775cf5c0f25'
down_revision = 'b617e1951d6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dev_environment_test_logs',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('reply', sa.String(), nullable=False),
    sa.Column('predicted_language', sa.String(), nullable=False),
    sa.Column('predicted_dimension_number', sa.Integer(), nullable=False),
    sa.Column('predicted_dimension_label', sa.String(), nullable=False),
    sa.Column('pattern_reconstructed', sa.String(), nullable=False),
    sa.Column('pattern_found', sa.String(), nullable=False),
    sa.Column('pattern_matching_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_lang_correct', sa.Boolean(), nullable=False),
    sa.Column('is_reply_correct', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dev_environment_test_logs')
    # ### end Alembic commands ###
