"""empty message

Revision ID: be70e144e8d6
Revises: a4660a9aa9bc
Create Date: 2023-12-09 02:23:05.603540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be70e144e8d6'
down_revision = 'a4660a9aa9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usability_test_logs',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.String(), nullable=False),
    sa.Column('reply', sa.String(), nullable=False),
    sa.Column('predicted_language', sa.String(), nullable=False),
    sa.Column('predicted_score', sa.Numeric(precision=3, scale=15), nullable=True),
    sa.Column('pattern_found', sa.String(), nullable=False),
    sa.Column('original_pattern_found', sa.String(), nullable=True),
    sa.Column('pattern_matching_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_lang_correct', sa.Boolean(), nullable=True),
    sa.Column('is_information_retrieved_valid', sa.Boolean(), nullable=True),
    sa.Column('is_query_within_domain', sa.Boolean(), nullable=True),
    sa.Column('test_number', sa.Integer(), nullable=True),
    sa.Column('reconstructed_message', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usability_test_logs')
    # ### end Alembic commands ###
